version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build

artifacts:
  files:
    - 'package.json'
    - 'nuxt.config.js'
    - '.nuxt/**/*'
    - 'static/**/*'
    - '.platform/**/*'
    - '.ebextensions/**/*'
